[package]
name = "sgn_stake_master"
version = "0.7.0"
cairo-version = "2.5.3"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.12.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.9.0" }
starknet = "2.5.3"


[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = false

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true
